---
- name: Verify
  hosts: all
  tasks:

  # NOTE that verify.yml does not inherit values from your playbook in anyway, they are seperate playbooks and run seperately.
  - name: set some stuff
    set_fact:
      package_list_command: "pacman -Q | awk '{print $1}'"
      homedir: "{{ ansible_env.HOME }}"

  # define files, packages, services & ports here, they will be checked in verify_standard.yml
  - name: define packages, files, directories and other stuff you want to check lots of
    set_fact:
      required_files:
        - path: "{{ homedir }}/.zsh"
          isdir: true
        - path: "{{ homedir }}/.zsh/functions"
          isdir: true
        - path: "{{ homedir }}/.zsh/aliases"
          isdir: false
        - path: "{{ homedir }}/.zsh/zshrc"
          isdir: false
        - path: "{{ homedir }}/.zsh/p10k.zsh"
          isdir: false
        - path: "{{ homedir }}/.zshrc"
          isdir: false
        - path: "{{ homedir }}/.ssh"
          isdir: true
      required_packages:
        - antigen
        - zsh
        - zsh-autosuggestions
        - zsh-theme-powerlevel10k
#      required_services:
#      required_ports:

  - name: include the standard verifier
    include_tasks: verify_standard.yml

# Add role specific tests here
